[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["migrations", "libs", "dev_mobile", "design", "deployment"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "DJ", "I"]
