# Generated by Django 5.1.3 on 2025-03-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='crawling_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='crawling_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='visited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='website',
            name='start_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
