# Generated by Django 5.1.3 on 2025-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_website_crawling_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='structured_text',
            field=models.JSONField(default=dict),
        ),
    ]
