# Generated by Django 5.1.3 on 2025-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedkeyword',
            name='interest_by_region',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedkeyword',
            name='interest_over_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedkeyword',
            name='related_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedkeyword',
            name='trend_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
