# Generated by Django 5.1.3 on 2025-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_website_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
