# Generated by Django 5.1.6 on 2025-04-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cta_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_recommendations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
