# Generated by Django 5.1.6 on 2025-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_seorecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='external_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='internal_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
