# Generated by Django 5.1.3 on 2025-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_page_favicon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='favicon_url',
        ),
        migrations.AddField(
            model_name='website',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
