# Generated by Django 5.1.3 on 2025-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_remove_page_cta_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='insight_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
