# Generated by Django 5.1.3 on 2025-04-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_website_insight_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_speed_score', models.FloatField(blank=True, null=True)),
                ('time_to_first_byte', models.FloatField(blank=True, null=True)),
                ('first_contentful_paint', models.FloatField(blank=True, null=True)),
                ('fully_loaded', models.FloatField(blank=True, null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loading_time', to='analysis.page')),
            ],
        ),
    ]
