# Generated by Django 5.1.3 on 2025-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_loadingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='scraping_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
