# Generated by Django 5.1.3 on 2025-04-22 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_website_positioning_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='partners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OverallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.TextField(blank=True, null=True)),
                ('usp', models.TextField(blank=True, null=True)),
                ('social_media', models.TextField(blank=True, null=True)),
                ('seo', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('partners', models.TextField(blank=True, null=True)),
                ('positioning_weaknesses', models.TextField(blank=True, null=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_analysis', to='analysis.website')),
            ],
        ),
    ]
