# Generated by Django 5.1.3 on 2025-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_website_partners_overallanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallanalysis',
            name='backend_stack',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overallanalysis',
            name='technology_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
