# Generated by Django 5.1.3 on 2025-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_overallanalysis_backend_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallanalysis',
            name='technology',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
