# Generated by Django 5.1.3 on 2025-04-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_alter_overallanalysis_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='analyzed',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='external_links',
        ),
        migrations.RemoveField(
            model_name='page',
            name='internal_links',
        ),
        migrations.RemoveField(
            model_name='page',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='linking_analysis',
        ),
        migrations.RemoveField(
            model_name='page',
            name='links',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_score',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_score_details',
        ),
        migrations.RemoveField(
            model_name='page',
            name='structured_data',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text_readability',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text_reading_time',
        ),
        migrations.RemoveField(
            model_name='page',
            name='text_types',
        ),
        migrations.RemoveField(
            model_name='page',
            name='warnings',
        ),
        migrations.CreateModel(
            name='PageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_analysis', models.JSONField(blank=True, null=True)),
                ('linking_analysis', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=42, null=True)),
                ('warnings', models.JSONField(blank=True, default=dict, null=True)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('internal_links', models.JSONField(blank=True, default=list, null=True)),
                ('external_links', models.JSONField(blank=True, default=list, null=True)),
                ('links', models.JSONField(blank=True, default=dict, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('seo_score_details', models.JSONField(blank=True, null=True)),
                ('text_types', models.JSONField(blank=True, default=dict, null=True)),
                ('text_readability', models.FloatField(blank=True, null=True)),
                ('text_reading_time', models.FloatField(blank=True, null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.page')),
            ],
        ),
        migrations.DeleteModel(
            name='KeywordInsight',
        ),
    ]
