# Generated by Django 5.1.3 on 2025-04-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_pageanalysis_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='partners',
        ),
    ]
