# Generated by Django 5.1.3 on 2025-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_remove_website_insight_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedkeyword',
            name='trends_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
