# Generated by Django 5.1.6 on 2025-03-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_element', models.CharField(choices=[('title', 'Title'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6'), ('alt', 'Alt'), ('p', 'Paragraph')], max_length=10)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('page_title', models.CharField(max_length=255)),
                ('last_visit', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.URLField(max_length=500)),
                ('last_visited', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedURL',
        ),
        migrations.AddField(
            model_name='keyword',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='analysis.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='analysis.website'),
        ),
    ]
