# Generated by Django 5.1.3 on 2025-03-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_page_structured_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_keywords', to='analysis.page')),
            ],
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
