# Generated by Django 5.1.6 on 2025-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_extractedkeyword_delete_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
