# Generated by Django 5.1.3 on 2025-03-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_extractedkeyword_interest_by_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='analysis.website')),
            ],
        ),
    ]
