# Generated by Django 5.1.6 on 2025-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_keywordinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_types',
            field=models.JSONField(default=dict),
        ),
    ]
