# Generated by Django 5.1.3 on 2025-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_page_text_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_readability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_reading_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
