# Generated by Django 5.1.6 on 2025-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_page_text_readability_page_text_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='target_audience',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
