# Generated by Django 5.1.6 on 2025-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_page_content_hash_page_description_page_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
