# Generated by Django 5.1.6 on 2025-04-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_page_cta_analysis_page_seo_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('actions', models.JSONField()),
                ('rationale', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.page')),
            ],
        ),
    ]
