# Generated by Django 5.1.6 on 2025-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_page_external_links_page_internal_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='linking_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_score_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
