# Generated by Django 5.1.3 on 2025-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_page_linking_analysis_page_seo_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
