# Generated by Django 5.1.3 on 2025-04-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_remove_page_favicon_url_website_favicon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='cta_analysis',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_recommendations',
        ),
        migrations.AlterField(
            model_name='page',
            name='external_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
