# Generated by Django 5.1.3 on 2025-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_website_scraping_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingtime',
            name='largest_contentful_paint',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
