# Generated by Django 5.1.3 on 2025-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_loadingtime_largest_contentful_paint'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='positioning_insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
