# Generated by Django 5.1.3 on 2025-04-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_remove_website_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='insight_text',
        ),
    ]
